services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: credix-api
    ports:
      - "8000:8000"
    volumes:
      - ./assets:/app/assets
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    container_name: credix-streamlit
    ports:
      - "8501:8501"
    environment:
      API_URL: "http://api:8000/predict"
    depends_on:
      - api
    restart: unless-stopped

  airflow-webserver:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: credix-airflow-webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW_UID: "50000"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - .:/opt/airflow/credix
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Karen
      --lastname Credix
      --role Admin
      --email admin@credix.com || true &&
      exec airflow webserver
      "
    restart: unless-stopped

  airflow-scheduler:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: credix-airflow-scheduler
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW_UID: "50000"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - .:/opt/airflow/credix
    command: airflow scheduler
    depends_on:
      - airflow-webserver
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: credix-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data:
